### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by riley8084** [Lyall/Octopath2Fix#2]
I've extracted the folder and it will not work, I'm also not sure what all to change in the .ini

I changed the HUD center to 21:9 but that didn't work either.

not sure if I'm supposed to keep all of the contents in the fix-master folder or not.

I extracted both ways and neither worked.

I'm probably just doing something wrong, any help would be appreciated :)

**Comment by Lyall** [comment]
It sounds like you downloaded the source code instead of the release. You want to go to the [releases page](https://github.com/Lyall/Octopath2Fix/releases) and download the release zip.

![image](https://user-images.githubusercontent.com/695941/227746252-f569efa4-6eec-45ab-9a2c-85017bcf7c10.png)

Then you extract that to the game folder, i.e `"steamapps\common\Octopath_Traveler2"`.

Also you shouldn't need to change anything in the ini unless you want to disable features. Everything is enabled by default so that means, unlocked framerate, centered 16:9 HUD and fixed aspect ratio/FOV.

**Comment by riley8084** [comment]
that did it haha, thankyou!
