### ISSUE TITLE
High GPU Usage

### ISSUE THREAD

**Issue by ConnorCraig39** [Lyall/Octopath2Fix#4]
While mod installed I am getting around 90-100% GPU usage in Task Manager. With mod not installed I get around 10-20% GPU Usage. Definitely shouldn't be getting this much GPU usage in this game. I tried turning on the frame limiter as well with no luck. 

System specs:
Intel Core i9-13900K
RTX 4090
64 GB DDR5-6000

Just wanted to also add, **amazing work here**. I've been really looking forward to a ultrawide fix for this game and finally got it lol, just hoping I can play without constant 100% GPU usage.

**Comment by Lyall** [comment]
That's odd, could you upload your log file? I can't think of any reason for a massive increase in GPU usage other than the 120FPS cap being removed by default. Could you try also try disabling that part of the fix in the ini?

**Comment by ConnorCraig39** [comment]
Okay I think that is the culprit! This happens when I enable the **Uncap FPS** setting. I checked the FPS and it was running at 850FPS. When I disable that setting, I am only getting around 10-20% GPU usage. Unsure whether this would be possible, but would you be able to introduce a custom fps variable or such - maybe to cap it to like 165fps or 240fps, etc.? Since my monitor refresh rate only goes up to 165 currently. Thank you!

**Comment by ConnorCraig39** [comment]
[Octopath2Fix.log](https://github.com/Lyall/Octopath2Fix/files/11114989/Octopath2Fix.log)
Here is the log file as well if it helps! Let me know if you need any further info.

**Comment by Lyall** [comment]
This make sense. In retrospect I think I should have left the FPS uncap off by default so that people don't run in to this type of issue. I could look at adding custom values but I think it's best if someone has FPS uncap on to just cap the framerate externally with something like the Nvidia control panel or RTSS, or just use vertical sync for simplicity. 

In your case just enabling the FPS uncap and using vertical sync should do the job of capping the framerate to your monitor's refresh rate. You can also cap the fps using the Nvidia control panel, in fact I'd recommend doing this if you're running a GSync display (which I assume you are given your amazing rig!). I personally run with a framerate cap just below my monitor's refresh rate so that it always takes advantage of GSync/Adaptive Sync. 

So for example if you had a 165hz display, you would enable vsync in the global tab and set the max frame rate limit to 162.

![image](https://user-images.githubusercontent.com/695941/228941805-f2e41ed9-e0b5-4a62-a776-1e615ba139d0.png)
