### ISSUE TITLE
Screen transition issue 

### ISSUE THREAD

**Issue by presstart2begn** [Lyall/Octopath2Fix#8]
The fix is working great for me for the most part on steam deck with the updated fix however anytime the game transitions in and out of cutscenes or in and out of battles the black fade screen is not a full screen transition and displays random images on the top and bottom of the screen

**Comment by johowoo** [comment]
I am having the same issue as well

**Comment by presstart2begn** [comment]
There is a newer version of the fix use that and it fixes the issue !

**Comment by johowoo** [comment]
![octopathTraveler2](https://github.com/Lyall/Octopath2Fix/assets/38002337/f70d84d9-f3b0-4ea7-8a9c-213d6c55414a)
@presstart2begn 
Thanks. I have tried with the latest v0.0.6, but the issue still exists
By the way, I am using a 32:9 screen with a resolution of 5120*1440, not sure if it is because my setup

**Comment by Lyall** [comment]
Fixed in [v0.9.0](https://github.com/Lyall/Octopath2Fix/releases).
